# =============================
# ðŸš€ Railway Laravel Nixpacks
# =============================

[build]
builder = "NIXPACKS"
version = "2"   # Ø£ÙŠ ØªØºÙŠÙŠØ± Ù‡Ù†Ø§ = Clear Cache Ø¥Ø¬Ø¨Ø§Ø±ÙŠ

[build.nixpacks]
phases = ["php", "node"]

